### ISSUE TITLE
Need Help using v-motion

### ISSUE THREAD

**Issue by Weaternwizard** [anaskhonprime/vuejs-tailwind-portfolio#5]
Can anyone help me with using v-motion? 
When i use v-motion for vue animations, nothing animated and Here the code as you used.

` v-motion
            :initial="{ opacity: 0, y: 200 }"
            :visible="{ opacity: 1, y: 0 }"
            :delay="1000" `

**Comment by anaskhonprime** [comment]
Good evening, for using v-motion, you need install and set main.js

[ Oficial Documentation ]

[https://motion.vueuse.org/](url)

 1. install @vueuse/motion

`npm add @vueuse/motion`

2. set src/main.js
```
import { MotionPlugin } from @vueuse/motion

const app = createApp(App)

app.use(MotionPlugin)

app.mount('#app')
```

i hope it will work^^

**Comment by Weaternwizard** [comment]
Oh, it works, Thansk~
